apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - web-tests.yaml

configMapGenerator:
  - files:
      - pre-test.sh
      - test.sh
      - post-test.sh
    name: scripts
